# SommOS Production Deployment Configuration
# Docker Compose configuration for production deployment

services:
  sommos-app:
    build: 
      context: ..
      dockerfile: Dockerfile.prod
    container_name: sommos-production
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_PATH=/app/data/sommos.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPEN_METEO_API_KEY=${OPEN_METEO_API_KEY}
    volumes:
      - sommos-data:/app/data
      - sommos-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=sommos"

  sommos-reverse-proxy:
    image: nginx:alpine
    container_name: sommos-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - sommos-logs:/var/log/nginx
    depends_on:
      - sommos-app
    labels:
      - "com.docker.compose.project=sommos"

volumes:
  sommos-data:
    driver: local
  
  sommos-logs:
    driver: local

networks:
  default:
    name: sommos-network